name: Docker Image CI

on:
  push:
    branches: [ master ]
    tags:
      - 'v-[0-9]+-[0-9]+-[0-9]+.[0-9]+'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            metabrainz/sshd
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=tag
          flavor: |
            latest=auto
            prefix=
            suffix=
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build (without cache) and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          labels: ${{ steps.meta.outputs.labels }}
          no-cache: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
